### ISSUE TITLE
bug: test without config file

### ISSUE THREAD

**Issue by esdandreu** [AcousticOdometry/VAO-recorder#1]
`recorder test microphone`
Not handled exception
```
No configuration found in C:\Users\SRG_Adams\Documents\Andreu\python-recorder.yaml. Generate one.
Traceback (most recent call last):
  File "C:\Users\SRG_Adams\Documents\Andreu\venv\lib\site-packages\recorder\__main__.py", line 148, in get_config
    return Config.from_yaml(path)
  File "C:\Users\SRG_Adams\Documents\Andreu\venv\lib\site-packages\recorder\config.py", line 17, in from_yaml
    raise AttributeError(f'Configuration file {path} does not exist')
AttributeError: Configuration file C:\Users\SRG_Adams\Documents\Andreu\python-recorder.yaml does not exist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\SRG_Adams\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\SRG_Adams\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\SRG_Adams\Documents\Andreu\venv\Scripts\recorder.exe\__main__.py", line 7, in <module>
  File "C:\Users\SRG_Adams\Documents\Andreu\venv\lib\site-packages\typer\main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "C:\Users\SRG_Adams\Documents\Andreu\venv\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\SRG_Adams\Documents\Andreu\venv\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\SRG_Adams\Documents\Andreu\venv\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\SRG_Adams\Documents\Andreu\venv\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\SRG_Adams\Documents\Andreu\venv\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\SRG_Adams\Documents\Andreu\venv\lib\site-packages\typer\main.py", line 500, in wrapper
    return callback(**use_params)  # type: ignore
  File "C:\Users\SRG_Adams\Documents\Andreu\venv\lib\site-packages\recorder\__main__.py", line 188, in test
    config = get_config(config_path)
  File "C:\Users\SRG_Adams\Documents\Andreu\venv\lib\site-packages\recorder\__main__.py", line 151, in get_config
    return Config.from_yaml(path)
  File "C:\Users\SRG_Adams\Documents\Andreu\venv\lib\site-packages\recorder\config.py", line 17, in from_yaml
    raise AttributeError(f'Configuration file {path} does not exist')
AttributeError: Configuration file C:\Users\SRG_Adams\Documents\Andreu\python-recorder.yaml does not exist
```

**Comment by esdandreu** [comment]
Solved in 4c40e36eb7640a6e649ff2430e64425191c4443c
